name: On Push Matrix

on:
  push:
    branches:
      - main

jobs:
  matrixJob:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        client: [client1, client2, iqbals-mining-operation]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: run matrix
        run: |
          echo "Node version: ${{ matrix.node-version }}"
          echo "Client: ${{ matrix.client }}"