name: On Push

on:
  push:
    branches:
      - main

jobs:
  push_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: execute script
        run: |
          echo "executing this script"

      - name: execute npm script
        shell: bash
        run: |
          npm run build
